name: Build and publish on a tag

on: 
  push:
    tags:
    - "*"

jobs:
  build-and-publish-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # Running this job only for tags

    steps:
    - uses: actions/checkout@v2.5.0

    - name: Build and Publish Tag Docker image
      uses: VaultVulp/gp-docker-action@1.5.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: my-cool-service # Provide only Docker image name
        extract-git-tag: true # Provide flag to extract Docker image tag from git reference
